#!/usr/bin/env python3
"""
Visualize preflop EHS fine values for all 169 canonical hand classes.

Produces two figures saved to clusters/:
  1. preflop_ehs_matrix.png  — 13×13 hand-matrix heatmap
  2. preflop_ehs_ranking.png — ranked bar chart of all 169 hands

Requires:
  clusters/preflop_ehs_fine.bin (generated by preflop_ehs_pipeline.py)

Nathaniel Potter, 03-27-2026
"""

import os
import sys

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

OUTPUT_DIR   = os.path.join(os.path.dirname(__file__), "..", "clusters")
EHS_PATH     = os.path.join(OUTPUT_DIR, "preflop_ehs_fine.bin")
MATRIX_OUT   = os.path.join(OUTPUT_DIR, "preflop_ehs_matrix.png")
RANKING_OUT  = os.path.join(OUTPUT_DIR, "preflop_ehs_ranking.png")

NUM_HANDS = 169

# Rank chars used by hand_indexer (matches RANK_CHARS in bindings.cpp)
_RANK_CHARS = "23456789TJQKA"   # index 0='2', index 12='A'
_SUIT_CHARS = "cdhs"


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_ehs(path: str) -> np.ndarray:
    """Load 169 uint16-quantized EHS values from binary file and decode to float32."""
    if not os.path.isfile(path):
        sys.exit(
            f"Error: EHS file not found: {path}\n"
            "Run preflop_ehs_pipeline.py first."
        )
    data = np.fromfile(path, dtype=np.uint16).astype(np.float32) / 65535.0
    if len(data) != NUM_HANDS:
        sys.exit(f"Error: expected {NUM_HANDS} values, got {len(data)}")
    return data


def try_import_indexer():
    """Import PreflopIndexer from the hand_indexer pybind module."""
    try:
        from hand_indexer import PreflopIndexer
        return PreflopIndexer()
    except ImportError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return None


# ---------------------------------------------------------------------------
# Hand info: build canonical metadata for all 169 indices
# ---------------------------------------------------------------------------

def _parse_card(card_str: str):
    """Parse a card string like 'As' into (rank_idx, suit_idx).

    rank_idx: position in "23456789TJQKA"  (0=deuce, 12=ace)
    suit_idx: position in "cdhs"
    """
    return _RANK_CHARS.index(card_str[0]), _SUIT_CHARS.index(card_str[1])


def build_hand_info(indexer) -> list:
    """Return list of dicts with canonical metadata for indices 0..168.

    Each dict:
      idx    canonical index
      name   short canonical name, e.g. "AKs", "AA", "AKo"
      high   rank index of the higher card  (0=2, 12=A)
      low    rank index of the lower card
      suited bool
      pair   bool
    """
    hands = []
    for idx in range(NUM_HANDS):
        raw    = indexer.unindex(idx)        # e.g. "Kc As"
        parts  = raw.split()                 # ["Kc", "As"]
        r1, s1 = _parse_card(parts[0])
        r2, s2 = _parse_card(parts[1])

        high   = max(r1, r2)
        low    = min(r1, r2)
        is_pair   = (r1 == r2)
        is_suited = (s1 == s2) and not is_pair

        hr = _RANK_CHARS[high]
        lr = _RANK_CHARS[low]
        if is_pair:
            name = hr + hr
        elif is_suited:
            name = hr + lr + "s"
        else:
            name = hr + lr + "o"

        hands.append(
            dict(idx=idx, name=name, high=high, low=low,
                 suited=is_suited, pair=is_pair)
        )
    return hands


# ---------------------------------------------------------------------------
# Figure 1: 13×13 heatmap
# ---------------------------------------------------------------------------

def build_matrix(hand_info, ehs_values):
    """Build 13×13 arrays (ehs, names) for the hand matrix.

    Display index d = 12 - rank  →  d=0 is Ace, d=12 is Deuce.
    Upper triangle  (row d < col d) : suited
    Diagonal        (row d = col d) : pairs
    Lower triangle  (row d > col d) : offsuit
    """
    mat   = np.full((13, 13), np.nan, dtype=np.float64)
    names = np.full((13, 13), "", dtype=object)

    for h in hand_info:
        ehs  = float(ehs_values[h["idx"]])
        hi_d = 12 - h["high"]
        lo_d = 12 - h["low"]

        if h["pair"]:
            mat[hi_d, hi_d]   = ehs
            names[hi_d, hi_d] = h["name"]
        elif h["suited"]:
            # hi_d < lo_d because high rank > low rank  →  upper triangle
            mat[hi_d, lo_d]   = ehs
            names[hi_d, lo_d] = h["name"]
        else:
            # offsuit: swap to lower triangle
            mat[lo_d, hi_d]   = ehs
            names[lo_d, hi_d] = h["name"]

    return mat, names


def plot_matrix(mat, names, ehs_values, out_path):
    """Figure 1: 13×13 EHS heatmap."""
    vmin = float(np.nanmin(mat))
    vmax = float(np.nanmax(mat))

    fig, ax = plt.subplots(figsize=(14, 12))
    cmap = plt.cm.RdYlGn
    im   = ax.imshow(mat, cmap=cmap, vmin=vmin, vmax=vmax, aspect="equal")

    # Annotate cells
    mid = (vmin + vmax) / 2
    for r in range(13):
        for c in range(13):
            if np.isnan(mat[r, c]):
                continue
            v      = mat[r, c]
            bright = cmap((v - vmin) / (vmax - vmin))[:3]
            # perceived luminance
            lum    = 0.299 * bright[0] + 0.587 * bright[1] + 0.114 * bright[2]
            tcolor = "black" if lum > 0.45 else "white"
            ax.text(c, r, f"{names[r, c]}\n{v:.3f}",
                    ha="center", va="center", fontsize=6.5,
                    color=tcolor, fontweight="bold", linespacing=1.3)

    rank_labels = [_RANK_CHARS[12 - d] for d in range(13)]  # A K Q … 2
    ax.set_xticks(range(13))
    ax.set_yticks(range(13))
    ax.set_xticklabels(rank_labels, fontsize=11)
    ax.set_yticklabels(rank_labels, fontsize=11)
    ax.tick_params(length=0)

    # Axis role labels
    ax.text(0.5, -0.06, "suited  ↗  (second card rank, upper-right)",
            ha="center", va="center", transform=ax.transAxes,
            fontsize=9, color="#1565C0", fontstyle="italic")
    ax.text(-0.06, 0.5, "offsuit  ↙  (lower-left)",
            ha="center", va="center", transform=ax.transAxes,
            fontsize=9, color="#B71C1C", fontstyle="italic", rotation=90)

    cbar = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    cbar.set_label("EHS (Equity Head-to-Showdown)", fontsize=11)
    cbar.ax.yaxis.set_tick_params(labelsize=9)

    ax.set_title(
        "Preflop EHS — 13×13 Hand Matrix\n"
        "upper-right: suited  │  diagonal: pairs  │  lower-left: offsuit",
        fontsize=13, fontweight="bold", pad=14,
    )

    plt.tight_layout()
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    print(f"Matrix figure saved to {out_path}")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Figure 2: Ranked bar chart
# ---------------------------------------------------------------------------

def plot_ranking(hand_info, ehs_values, out_path):
    """Figure 2: horizontal bar chart of all 169 hands ranked by EHS."""
    order = sorted(hand_info, key=lambda h: float(ehs_values[h["idx"]]))

    bar_names  = [h["name"]                    for h in order]
    bar_values = [float(ehs_values[h["idx"]]) for h in order]

    bar_colors = []
    for h in order:
        if h["pair"]:
            bar_colors.append("#4CAF50")   # green
        elif h["suited"]:
            bar_colors.append("#1565C0")   # blue
        else:
            bar_colors.append("#CC2222")   # red

    fig, ax = plt.subplots(figsize=(10, 22))

    y_pos = np.arange(len(order))
    ax.barh(y_pos, bar_values, color=bar_colors, height=0.80, edgecolor="none")

    # EHS labels on bars
    x_max = max(bar_values)
    for i, v in enumerate(bar_values):
        ax.text(v + 0.003, i, f"{v:.3f}", va="center", fontsize=5.5,
                color="#222222")

    ax.set_yticks(y_pos)
    ax.set_yticklabels(bar_names, fontsize=7, fontfamily="monospace")
    ax.set_xlabel("EHS (Equity Head-to-Showdown)", fontsize=11)
    ax.set_xlim(0, x_max + 0.06)

    # Quartile lines
    arr = np.array(bar_values)
    for pct, label in [(25, "Q1"), (50, "Q2"), (75, "Q3")]:
        q = float(np.percentile(arr, pct))
        ax.axvline(q, color="#888888", ls="--", lw=0.9, alpha=0.8, zorder=0)
        ax.text(q, len(order) - 0.5, label, ha="center", va="bottom",
                fontsize=8, color="#666666")

    # Legend
    legend_elements = [
        Patch(facecolor="#4CAF50", label="Pairs (13)"),
        Patch(facecolor="#1565C0", label="Suited (78)"),
        Patch(facecolor="#CC2222", label="Offsuit (78)"),
    ]
    ax.legend(handles=legend_elements, loc="lower right", fontsize=9)

    ax.set_title(
        "Preflop EHS — All 169 Canonical Hands Ranked\n"
        "green = pairs   blue = suited   red = offsuit",
        fontsize=13, fontweight="bold",
    )
    ax.grid(axis="x", alpha=0.25)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    plt.tight_layout()
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    print(f"Ranking figure saved to {out_path}")
    plt.close(fig)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ehs_path    = os.path.abspath(EHS_PATH)
    matrix_out  = os.path.abspath(MATRIX_OUT)
    ranking_out = os.path.abspath(RANKING_OUT)

    ehs = load_ehs(ehs_path)
    print(f"Loaded {len(ehs)} preflop EHS values")
    print(f"  range: [{ehs.min():.4f}, {ehs.max():.4f}]  mean: {ehs.mean():.4f}")

    indexer = try_import_indexer()
    if indexer is None:
        sys.exit("hand_indexer pybind module is required.")

    hand_info = build_hand_info(indexer)

    mat, cell_names = build_matrix(hand_info, ehs)
    plot_matrix(mat, cell_names, ehs, matrix_out)
    plot_ranking(hand_info, ehs, ranking_out)


if __name__ == "__main__":
    main()
